name = "livestore-todomvc"
main = "src/worker.tsx"
compatibility_date = "2025-05-07"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true